### ISSUE TITLE
Embedded images on HTML preview

### ISSUE THREAD

**Issue by nexces** [mailhog/MailHog#27]
Any chance to make it happen? :)

**Comment by ian-kent** [comment]
Yep, always meant to just haven't got around to it yet :smile:

**Comment by ian-kent** [comment]
I think this is fixed, but I'll keep this open until I've had a chance to test it properly

**Comment by bunam** [comment]
With https://github.com/mailhog/MailHog/releases/v0.2.0 (linux 386 on CentOS 5)
the bug isn't fixed
Mails was well displayed with mailcatcher ;p

**Comment by ian-kent** [comment]
accidental close!

@bunam could you provide logs and example messages please :smile:

**Comment by Fuco1** [comment]
This still seems to not work.  When I send the same email via mandrill to my gmail inbox things render properly.

**Comment by henno** [comment]
Example message: https://pastebin.com/KnenaHvR

**Comment by brice** [comment]
I can try to help. I don't think this is something that we can correct in this project but probably in a sub project. Is someone can help me to investigate, i'm kinda new in Go.

**Comment by iansebryk** [comment]
for what it's worth, problem still exists.  😝 except images aren't rendering *at all* now.  😞

**Comment by nmoreaud** [comment]
up

**Comment by cprn** [comment]
Linked example is not a correct image, according to ISO you . The following structure renders correctly in MailHog:

```
multipart/related
├── multipart/alternative
│   ├── text/plain
│   └── text/html
└── image/png
```

The following doesn't render embedded images as it should - note it's same structure but wrapped in mixed because there's an extra PDF file attached:
```
multipart/mixed
├── multipart/related
│   ├── multipart/alternative
│   │   ├── text/plain
│   │   └── text/html
│   └── image/png
└── application/pdf
```

[Correct example](https://gist.github.com/cprn/3e6887690e513fd8f90332324355bbea) - first doesn't work, second does.

**Comment by jeserkin** [comment]
Just tried sending email and mail client shows image, but mailhog ui shows 
![image](https://user-images.githubusercontent.com/183512/105813484-91393a00-5fb8-11eb-906f-2cbd8dd37f2e.png)

**Comment by stappersg** [comment]
FWIW: Now that https://github.com/tweedegolf/mailcrab/issues/62 is _closed as completed_ is [`mailcrab`](https://github.com/tweedegolf/mailcrab/) able to show embedded images.
